python=3.14.4
pip
langchain=0.2.16
langchain-core=0.2.43
langchain-community=0.2.17
langchain-openai=0.1.25
langchain-google-vertexai=3.2.3
langchain-text-splitters=0.2.4
langsmith=0.1.147
ragas=0.4.3
openai=1.109.1
pandas=2.3.3
python-dotenv=1.2.2
pymupdf=1.27.2.3
faiss-cpu=1.14.2
ipykernel=7.2.0